### ISSUE TITLE
Can't find static file if the route collides with the one set for feliz-bundle-js

### ISSUE THREAD

**Issue by hectormenendez** [gikmx/feliz-bundle-js#1]
```
Debug: internal, implementation, error 
gik.website-0     Error: Uncaught error: no such file or directory
gik.website-0     at MemoryFileSystem.readFileSync (/home/etor/www/gik.website/node_modules/memory-fs/lib/MemoryFileSystem.js:114:10)
gik.website-0     at webpack.run (/home/etor/www/gik.website/node_modules/feliz-bundle-js/lib/handler.js:48:28)
gik.website-0     at Compiler.<anonymous> (/home/etor/www/gik.website/node_modules/webpack/lib/Compiler.js:194:14)
gik.website-0     at Compiler.emitRecords (/home/etor/www/gik.website/node_modules/webpack/lib/Compiler.js:282:37)
gik.website-0     at Compiler.<anonymous> (/home/etor/www/gik.website/node_modules/webpack/lib/Compiler.js:187:11)
gik.website-0     at /home/etor/www/gik.website/node_modules/webpack/lib/Compiler.js:275:11
gik.website-0     at Compiler.applyPluginsAsync (/home/etor/www/gik.website/node_modules/tapable/lib/Tapable.js:60:69)
gik.website-0     at Compiler.afterEmit (/home/etor/www/gik.website/node_modules/webpack/lib/Compiler.js:272:8)
gik.website-0     at Compiler.<anonymous> (/home/etor/www/gik.website/node_modules/webpack/lib/Compiler.js:267:14)
gik.website-0     at /home/etor/www/gik.website/node_modules/async/lib/async.js:52:16
gik.website-0     at Object.async.forEachOf.async.eachOf (/home/etor/www/gik.website/node_modules/async/lib/async.js:236:30)
gik.website-0     at Object.async.forEach.async.each (/home/etor/www/gik.website/node_modules/async/lib/async.js:209:22)
gik.website-0     at Compiler.emitFiles (/home/etor/www/gik.website/node_modules/webpack/lib/Compiler.js:235:20)
gik.website-0     at MemoryFileSystem.(anonymous function) [as mkdirp] (/home/etor/www/gik.website/node_modules/memory-fs/lib/MemoryFileSystem.js:283:10)
gik.website-0     at Compiler.<anonymous> (/home/etor/www/gik.website/node_modules/webpack/lib/Compiler.js:229:25)
gik.website-0     at Compiler.applyPluginsAsync (/home/etor/www/gik.website/node_modules/tapable/lib/Tapable.js:60:69)
```

**Comment by hectormenendez** [comment]
This was a problem originated by the [feliz.bundler](http://github.com/gikmx/feliz.bundler), and it was solved on [#fa06c3](https://github.com/gikmx/feliz.bundler/commit/7826a6276ccf696a10efd49111eb66a1a6).

I updated the dependency to latest, and the problem is gone.
